language: elixir
elixir: '1.7'
otp_release: '21.0'
addons:
  postgresql: '9.4'
jobs:
  include:
    - &stage_test
      stage: test
      env: MIX_ENV=test
      services:
        - postgresql
      before_script:
        - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';"
      script:
        - mix coveralls.travis
    - <<: *stage_test
      env: MIX_ENV=integration
    - stage: docker
      services:
        - docker
      env: MIX_ENV=prod
      script:
        - docker build -t wanon:latest .
        - docker tag wanon:latest cloud.canister.io:5000/graffic/wanon:latest
        - echo "$CANISTER_PASSWORD" | docker login -u "$CANISTER_USERNAME" --password-stdin cloud.canister.io:5000
        - docker push cloud.canister.io:5000/graffic/wanon:latest
    - stage: deploy
      script:
        - curl -L https://github.com/dvddarias/rdocker/raw/master/rdocker.sh > rdocker
        - chmod +x rdocker
        - echo $DEPLOY_KEY > deploy_key
        - chmod 400 deploy_key
        - eval "$(ssh-agent -s)"
        - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ./rdocker $DEPLOY_HOST container ls
