language: elixir
elixir: '1.6'
otp_release: '21.0'

env:
  - MIX_ENV=test
  - MIX_ENV=integration

jobs:
  include:
    - stage: test
      services:
        - postgresql
      addons:
        postgresql: '9.4'
      before_script:
        - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';"
      script:
        - mix coveralls.travis
    - stage: deploy
      services:
        - docker
      env: MIX_ENV=prod
      script:
        - docker run --rm -v $PWD:/app graffic/elixir:alpine-arm64v8 "cd /app; mix deps.get"
